In [139]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

1. Load Iris dataset

In [114]:
iris = load_iris()

2. Create separate X and y datasets

In [115]:
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = pd.DataFrame(iris.target, columns=['target'])

3. Save following dataset to css

In [116]:
df = pd.concat([X, y], axis=1)
df.to_csv("iris.csv", index=False)

4. Read saved cv

In [117]:
df2 = pd.read_csv("iris.csv")
df2

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

5. Delete one column from dataset

In [118]:
df.drop('target', axis=1)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

6. Standardize your features except y 

Powinno byc po podziale danych ze wzgledu na wyciek danych

7. Split dataset to test/train

In [119]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=30)

8. Scale your data

In [120]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

9. Train logistics regression model

In [121]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train_scaled, y_train['target'])
# y_train

LogisticRegression(max_iter=1000)

10. Calculate accuracy

In [122]:
accuracy = model.score(X_test_scaled, y_test['target'])
accuracy

0.9333333333333333

11. Calculate predictions

In [123]:
predictions = model.predict(X_test_scaled)

12. Display model coefficients

In [131]:
pd.concat([pd.DataFrame(X.columns),pd.DataFrame(np.transpose(model.coef_))], axis = 1)

                   0         0         1         2
0  sepal length (cm) -0.986985  0.562116  0.424868
1   sepal width (cm)  1.081874 -0.347115 -0.734760
2  petal length (cm) -1.837011 -0.276304  2.113315
3   petal width (cm) -1.713264 -0.833519  2.546783

13. Show confusion matrix

In [140]:
confusion_matrix(y_test, predictions, labels=[0,1,2])

array([[12,  0,  0],
       [ 0,  8,  1],
       [ 0,  1,  8]])